### // Field order
POST http://localhost:8081/booking/order
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjUzMzIyODUsImlkIjoiOGNiMWViOGUtYmQyZS00NDEzLWI0ZDEtYWRiMzUyNTViMTIxIiwidXNlcm5hbWUiOiIrOTk4OTQ1MDIyMTQ3Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJyZWZyZXNoVG9rZW4iOmZhbHNlLCJleHAiOjE3MjU0MTg2ODUsImlzcyI6IlN0YWRpdW0ifQ.bUdHfuQe0pmY8eyt9KmxCaZjASJsRsacUvj5bSfSkLE5f5IdK3CTfXEgd4QeKEnbcMU9rYMughjKlpaqV_0_Rw
Accept-Language: UZ
Content-Type: application/json

{
  "fieldId": 3,
  "startTime": "2024-08-27T16:00:00",
  "endTime": "2024-08-27T16:30:00"
}
###  // Field order user
GET http://localhost:8081/booking/get-order-user?
    status=BOOKED
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjUzMzIyODUsImlkIjoiOGNiMWViOGUtYmQyZS00NDEzLWI0ZDEtYWRiMzUyNTViMTIxIiwidXNlcm5hbWUiOiIrOTk4OTQ1MDIyMTQ3Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJyZWZyZXNoVG9rZW4iOmZhbHNlLCJleHAiOjE3MjU0MTg2ODUsImlzcyI6IlN0YWRpdW0ifQ.bUdHfuQe0pmY8eyt9KmxCaZjASJsRsacUvj5bSfSkLE5f5IdK3CTfXEgd4QeKEnbcMU9rYMughjKlpaqV_0_Rw
Accept-Language: UZ

### // Field order owner field id
GET http://localhost:8081/booking/own/get-order-owner-field-id/3
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjUzMzIyODUsImlkIjoiOGNiMWViOGUtYmQyZS00NDEzLWI0ZDEtYWRiMzUyNTViMTIxIiwidXNlcm5hbWUiOiIrOTk4OTQ1MDIyMTQ3Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJyZWZyZXNoVG9rZW4iOmZhbHNlLCJleHAiOjE3MjU0MTg2ODUsImlzcyI6IlN0YWRpdW0ifQ.bUdHfuQe0pmY8eyt9KmxCaZjASJsRsacUvj5bSfSkLE5f5IdK3CTfXEgd4QeKEnbcMU9rYMughjKlpaqV_0_Rw
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjUzNjk3ODEsImlkIjoiOGNiMWViOGUtYmQyZS00NDEzLWI0ZDEtYWRiMzUyNTViMTIyIiwidXNlcm5hbWUiOiIrOTk4OTQ1MDIyMTQ4Iiwicm9sZSI6IlJPTEVfT1dORVIiLCJyZWZyZXNoVG9rZW4iOmZhbHNlLCJleHAiOjE3MjU0NTYxODEsImlzcyI6IlN0YWRpdW0ifQ.JoHtHCptAM0RBbFwZfkjZQzGbGmm2xE23cMuxmQB8XRRYCXR5ubgc4lt2gqmsBOv0WH6ZZxisjyUR98AoBFa6A
Accept-Language: UZ

### // Field order owner stadium id
GET http://localhost:8081/booking/own/get-order-owner-stadium-id/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjUzMzIyODUsImlkIjoiOGNiMWViOGUtYmQyZS00NDEzLWI0ZDEtYWRiMzUyNTViMTIxIiwidXNlcm5hbWUiOiIrOTk4OTQ1MDIyMTQ3Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJyZWZyZXNoVG9rZW4iOmZhbHNlLCJleHAiOjE3MjU0MTg2ODUsImlzcyI6IlN0YWRpdW0ifQ.bUdHfuQe0pmY8eyt9KmxCaZjASJsRsacUvj5bSfSkLE5f5IdK3CTfXEgd4QeKEnbcMU9rYMughjKlpaqV_0_Rw
Accept-Language: UZ