### 1. Region create
POST http://localhost:8080/region/adm/create
Content-Type: application/json
Authorization: Bearer

{
  "orderNumber": 6,
  "nameUz": "Jizzax",
  "nameRu": "Джизак",
  "nameEn": "Jizzakh"
}


### 2. Region update
PUT http://localhost:8080/region/adm/update/6
Content-Type: application/json
Authorization: Bearer

{
  "orderNumber": 6,
  "nameUz": "Jizzax",
  "nameRu": "Джизак",
  "nameEn": "Jizzakh"
}

### 3. Region list
GET http://localhost:8081/region/adm/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjQyMTkyMzQsImlkIjoiOGNiMWViOGUtYmQyZS00NDEzLWI0ZDEtYWRiMzUyNTViMTIxIiwidXNlcm5hbWUiOiIrOTk4OTQ1MDIyMTQ3Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJyZWZyZXNoVG9rZW4iOmZhbHNlLCJleHAiOjE3MjQzMDU2MzQsImlzcyI6IlN0YWRpdW0ifQ.uk7-NtHN2mR06noJ8IfXOMz8k6dtPrgroy6srF_aG8T5mkhQYlnOTCz7w-1OViJc-bPPARwRkR0MO3rPGhUF3A

### 4. Region delete
DELETE http://localhost:8080/region/adm/delete/1
Authorization: Bearer

### 5. Region By Lang
GET http://localhost:8081/region/lang
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjQxMzU1NjksImlkIjoiOGNiMWViOGUtYmQyZS00NDEzLWI0ZDEtYWRiMzUyNTViMTIxIiwidXNlcm5hbWUiOiIrOTk4OTQ1MDIyMTQ3Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJyZWZyZXNoVG9rZW4iOmZhbHNlLCJleHAiOjE3MjQyMjE5NjksImlzcyI6IlN0YWRpdW0ifQ.0bEsLzaH1s52LrZmaEWRqBM0p7olTRQ_WQ5IP7d62iqOUE2zJxj4VaJQGg0yb5FugEXxs_X4uahYItqY2YHi3Q
Accept-Language: KR
