INSERT INTO district(id, name_uz, name_en, name_ru, name_kr, region_id, created_date, visible, county)
values
    -- Tashkent Shahar
    (1, 'Bektemir', 'Bektemir', 'Бектемир', 'Бектемир', 1, now(), true, 'Bektemir Tumani'),
    (2, 'Mirobod', 'Mirabad', 'Мирабад', 'Мирабад', 1, now(), true, 'Mirobod Tumani'),
    (3, 'Mirzo Ulug‘bek', 'Mirzo Ulugbek', 'Мирзо-Улугбек', 'Мирзо-Улугбек', 1, now(), true, 'Mirzo Ulug‘bek Tumani'),
    (4, 'Sergeli', 'Sergely', 'Сергелий', 'Сергелий', 1, now(), true, 'Sergeli Tumani'),
    (5, 'Yangihayot', 'Yangihayat', 'Янги хаёт', 'Янги хаёт', 1, now(), true, 'Yangihayot Tumani'),
    (6, 'Olmazor', 'Almazar', 'Олмазор', 'Олмазор', 1, now(), true, 'Olmazor Tumani'),
    (7, 'Uchtepa', 'Uchtepa', 'Учтепa', 'Учтепа', 1, now(), true, 'Uchtepa Tumani'),
    (8, 'Shayxontohur', 'Shaikhontohur', 'Шайхонтохур', 'Шайхонтохур', 1, now(), true, 'Shayxontohur Tumani'),
    (9, 'Yashnobod', 'Yashnabad', 'Яшнобод', 'Яшнобод', 1, now(), true, 'Yashnobod Tumani'),
    (10, 'Chilonzor', 'Chilanzar', 'Чиланзар', 'Чиланзар', 1, now(), true, 'Chilonzor Tumani'),
    (11, 'Yunusobod', 'Yunusabad', 'Юнусабад', 'Юнусабад', 1, now(), true, 'Yunusobod Tumani'),
    (12, 'Yakkasaroy', 'Yakkasaray', 'Яккасарай', 'Яккасарай', 1, now(), true, 'Yakkasaroy Tumani'),

    -- Toshkent viloyati
    (13, 'Bekobod', 'Bekabad', 'Бекабад', 'Бекабад', 2, now(), true, 'Bekobod Tumani'),
    (14, 'Boʻstonliq', 'Bostonian', 'Бостанлык', 'Бостанлык', 2, now(), true, 'Boʻstonliq Tumani'),
    (15, 'Boʻka', 'Boka', 'Букинский', 'Букинский', 2, now(), true, 'Boʻka Tumani'),
    (16, 'Chinoz', 'Chinaz', 'Чиназ', 'Чиназ', 2, now(), true, 'Chinoz Tumani'),
    (17, 'Qibray', 'Kibrai', 'Кибрай', 'Кибрай', 2, now(), true, 'Qibray Tumani'),
    (18, 'Ohangaron', 'Ohangaron', 'Ахангаранский', 'Ахангарон', 2, now(), true, 'Ohangaron Tumani'),
    (19, 'Oqqoʻrgʻon', 'Okkorgan', 'Аккурган', 'Аккурган', 2, now(), true, 'Oqqoʻrgʻon Tumani'),
    (20, 'Parkent', 'Parkent', 'Паркент', 'Паркент', 2, now(), true, 'Parkent Tumani'),
    (21, 'Piskent', 'Piskent', 'Пскент', 'Пскент', 2, now(), true, 'Piskent Tumani'),
    (22, 'Quyi Chirchiq', 'Kuyi Chirchik', 'Куйичирчик', 'Куйи Чирчик', 2, now(), true, 'Quyi Chirchiq Tumani'),
    (23, 'Oʻrta Chirchiq', 'Urta Chirchik', 'Уртачирчик', 'Ўрта Чирчик', 2, now(), true, 'Oʻrta Chirchiq Tumani'),
    (24, 'Yangiyoʻl', 'Yangiyul', 'Янгиюльский', 'Янгийўл', 2, now(), true, 'Yangiyoʻl Tumani'),
    (25, 'Yuqori Chirchiq', 'Yukori Chirchik', 'Верхний Чирчик', 'Юқори Чирчик', 2, now(), true,
     'Yuqori Chirchiq Tumani'),
    (26, 'Zangiota', 'Zangiata', 'Зангиатa', 'Зангиота', 2, now(), true, 'Zangiota Tumani'),
    (27, 'Angren', 'Angren', 'Ангрен', 'Ангрен', 2, now(), true, 'Angren Tumani'),

-- Andijon
    (28, 'Oltinkoʻl', 'Oltinkul', 'Алтынкуль', 'Олтинкўл', 3, now(), true, 'Oltinkoʻl Tumani')
        ,
    (29, 'Andijon', 'Andijan', 'Андижан', 'Андижон', 3, now(), true, 'Andijon Tumani'),
    (30, 'Asaka', 'Asaka', 'Асака', 'Асака', 3, now(), true, 'Asaka Tumani'),
    (31, 'Baliqchi', 'Balikchi', 'Балыкчи', 'Балыкчи', 3, now(), true, 'Baliqchi Tumani'),
    (32, 'Boʻz', 'Buz', 'Боз', 'Боз', 3, now(), true, 'Boʻz Tumani'),
    (33, 'Buloqboshi', 'Bulokboshi', 'Булакбаши', 'Булакбаши', 3, now(), true, 'Buloqboshi Tumani'),
    (34, 'Qorasuv', 'Korasuv', 'Карасу', 'Қорасу', 3, now(), true, 'Qorasuv Tumani'),
    (35, 'Qoʻrgʻontepa', 'Kurgontepa', 'Кургантепа', 'Қўрғонтепа', 3, now(), true, 'Qoʻrgʻontepa Tumani'),
    (36, 'Marhamat', 'Marhamat', 'Мархамат', 'Марҳамат', 3, now(), true, 'Marhamat Tumani'),
    (37, 'Poytug', 'Poytug', 'Пайтуг', 'Пойтўғ', 3, now(), true, 'Poytug Tumani'),
    (38, 'Paxtaobod', 'Paxtaobod', 'Пахтабад', 'Пахтаобод', 3, now(), true, 'Paxtaobod Tumani'),
    (39, 'Shahrixon', 'Shahrihan', 'Шахрихан', 'Шаҳрихон', 3, now(), true, 'Shahrixon Tumani'),
    (40, 'Xonobod', 'Honabad', 'Ханабад', 'Хонобод', 3, now(), true, 'Xonobod Tumani'),
    (41, 'Xoʻjaobod', 'Hujabod', 'Ходжаабад', 'Ҳўжаобод', 3, now(), true, 'Xoʻjaobod Tumani'),
    (42, 'Jalaquduq', 'Jalaqoduk', 'Жалакудук', 'Жалақудуқ', 3, now(), true, 'Jalaquduq Tumani'),
    (43, 'Ulug‘nor', 'Ulugnor', 'Улугнор', 'Улуғнор', 3, now(), true, 'Ulug‘nor Tumani'),


-- Buxoro viloyati
    (44, 'Olot', 'Olot', 'Алат', 'Алат', 4, now(), true, 'Olot Tumani'),
    (45, 'Buxoro', 'Bukhara', 'Бухара', 'Бухара', 4, now(), true, 'Buxoro Tumani'),
    (46, 'Peshku', 'Peshku', 'Пешку', 'Пешку', 4, now(), true, 'Peshku Tumani'),
    (47, 'Gʻijduvon', 'Gijduvan', 'Гиждуван', 'Гиждуван', 4, now(), true, 'Gʻijduvon Tumani'),
    (48, 'Kogon', 'Kogon', 'Каган', 'Каган', 4, now(), true, 'Kogon Tumani'),
    (49, 'Qorakoʻl', 'Korakul', 'Каракуль', 'Қоракул', 4, now(), true, 'Qorakoʻl Tumani'),
    (50, 'Qorovulbozor', 'Korovulbazar', 'Караулбазар', 'Қораўулбозор', 4, now(), true, 'Qorovulbozor Tumani'),
    (51, 'Romitan', 'Romitan', 'Ромитан', 'Ромитан', 4, now(), true, 'Romitan Tumani'),
    (52, 'Shofirkon', 'Shofirkor', 'Шафиркан', 'Шофиркон', 4, now(), true, 'Shofirkon Tumani'),
    (53, 'Vobkent', 'Vobkent', 'Вабкент', 'Вобкент', 4, now(), true, 'Vobkent Tumani'),
    (54, 'Jondor', 'Jondor', 'Жондор', 'Жондор', 4, now(), true, 'Jondor Tumani'),

-- Jizzax viloyati
    (55, 'Arnasoy', 'Arnasoy', 'Арнасай', 'Арнасай', 5, now(), true, 'Arnasoy Tumani'),
    (56, 'Baxmal', 'Bahmal', 'Бахмал', 'Бахмал', 5, now(), true, 'Baxmal Tumani'),
    (57, 'Doʻstlik', 'Dustlik', 'Дустлик', 'Дустлик', 5, now(), true, 'Doʻstlik Tumani'),
    (58, 'Jizzax', 'Jizakh', 'Джизак', 'Джизак', 5, now(), true, 'Jizzax Tumani'),
    (59, 'Sharof Rashidov', 'Sharof Rashidov', 'Шаров Рашидов', 'Шароф Рашидов', 5, now(), true,
     'Sharof Rashidov Tumani'),
    (60, 'Gʻallaorol', 'Gallaorol', 'Галлаарал', 'Галлаорол', 5, now(), true, 'Gʻallaorol Tumani'),
    (61, 'Mirzacho‘l', 'Mirzachul', 'Мирзачол', 'Мирзачол', 5, now(), true, 'Mirzacho‘l Tumani'),
    (62, 'Paxtakor', 'Pakhtakor', 'Пахтакор', 'Пахтакор', 5, now(), true, 'Paxtakor Tumani'),
    (63, 'Yangiobod', 'Yangiobod', 'Янгабад', 'Янгиобод', 5, now(), true, 'Yangiobod Tumani'),
    (64, 'Forish', 'Forish', 'Фориш', 'Фориш', 5, now(), true, 'Forish Tumani'),
    (65, 'Zomin', 'Zomin', 'Заамин', 'Заамин', 5, now(), true, 'Zomin Tumani'),
    (66, 'Zafarobod', 'Zafarobod', 'Зафарабад', 'Зафарабад', 5, now(), true, 'Zafarobod Tumani'),
    (67, 'Zarbdor', 'Zarbdor', 'Зарбдар', 'Зарбдор', 5, now(), true, 'Zarbdor Tumani'),

-- Qoraqalpog'iston
    (68, 'Bo‘zatov', 'Buzatov', 'Бозатаусский', 'Бозатўл', 6, now(), true, 'Bo‘zatov rayonı'),
    (69, 'Beruniy', 'Beruni', 'Беруни', 'Беруний', 6, now(), true, 'Beruniy rayonı'),
    (70, 'Amudaryo', 'Amudarya', 'Амударьинский', 'Амударё', 6, now(), true, 'Amudaryo rayonı'),
    (71, 'Chimboy', 'Chimbay', 'Чимбай', 'Чимбай', 6, now(), true, 'Chimboy rayonı'),
    (72, 'Qonlikoʻl', 'Konlikul', 'Канлыкуль', 'Қонлиқўл', 6, now(), true, 'Qonlikoʻl rayonı'),
    (73, 'Qoraoʻzak', 'Koraozak', 'Караузяк', 'Қораўзоқ', 6, now(), true, 'Qoraoʻzak rayonı'),
    (74, 'Kegeyli', 'Kegeyli', 'Кегейли', 'Кегейли', 6, now(), true, 'Kegeyli rayonı'),
    (75, 'Qoʻngʻirot', 'Kongirot', 'Кунград', 'Қўңғират', 6, now(), true, 'Qoʻngʻirot rayonı'),
    (76, 'Ellikqal‘a', 'Ellikkala', 'Элликкалинский', 'Элликқала', 6, now(), true, 'Ellikqal‘a rayonı'),
    (77, 'Moʻynoq', 'Muynak', 'Муйнак', 'Мўйноқ', 6, now(), true, 'Moʻynoq rayonı'),
    (78, 'Nukus', 'Nukus', 'Нукус', 'Нўкус', 6, now(), true, 'Nukus rayonı'),
    (79, 'Shumanay', 'Shumanay', 'Шуманай', 'Шуманай', 6, now(), true, 'Shumanay rayonı'),
    (80, 'Taxtakoʻpir', 'Takhtakupir', 'Тахтакупыр', 'Тахтакўпир', 6, now(), true, 'Taxtakoʻpir rayonı'),
    (81, 'Toʻrtkoʻl', 'Turtkul', 'Турткуль', 'Тўртқул', 6, now(), true, 'Toʻrtkoʻl rayonı'),
    (82, 'Xoʻjayli', 'Kxujayli', 'Ходжейли', 'Хўжайли', 6, now(), true, 'Xoʻjayli rayonı'),

-- Qashqadaryo
    (83, 'Chiroqchi', 'Chirakchi', 'Чиракчи', 'Чиракчи', 7, now(), true, 'Chiroqchi Tumani'),
    (84, 'Dehqonobod', 'Dehkanabad', 'Дехканабад', 'Дехканабад', 7, now(), true, 'Dehqonobod Tumani'),
    (85, 'Gʻuzor', 'Guzar', 'Гузар', 'Гузар', 7, now(), true, 'Gʻuzor Tumani'),
--     (86, 'Qamashi', 'Kamashi', 'Камаши', 'Қамаши', 7, now(), true, 'Qamashi Tumani'),
    (87, 'Qarshi', 'Karshi', 'Карши', 'Қарши', 7, now(), true, 'Qarshi Tumani'),
    (88, 'Koson', 'Koson', 'Касан', 'Қосон', 7, now(), true, 'Koson Tumani'),
    (89, 'Kasbi', 'Kasbi', 'Касби', 'Қасби', 7, now(), true, 'Kasbi Tumani'),
    (90, 'Kitob', 'Kitab', 'Китаб', 'Китоб', 7, now(), true, 'Kitob Tumani'),
    (91, 'Muborak', 'Muborak', 'Мубарек', 'Муборак', 7, now(), true, 'Muborak Tumani'),
    (92, 'Qamashi', 'Kamashi', 'Камаши', 'Қамаши', 7, now(), true, 'Qamashi Tumani'),
    (93, 'Shahrisabz', 'Shahrisabz', 'Шахрисабз', 'Шаҳрисабз', 7, now(), true, 'Shahrisabz Tumani'),
    (94, 'Ko‘kdala', 'Kukdala', 'Кокдала', 'Кўкдала', 7, now(), true, 'Ko‘kdala Tumani'),
    (95, 'Yakkabog', 'Yakkabag', 'Яккабаг', 'Яккабоғ', 7, now(), true, 'Yakkabog’ Tumani'),
    (96, 'Mirishkor', 'Mirishkor', 'Миришкор', 'Миришкор', 7, now(), true, 'Mirishkor Tumani'),
    (97, 'Nishon', 'Nishan', 'Нишан', 'Нишон', 7, now(), true, 'Nishon Tumani'),

-- Navoiy viloyati
    (98, 'Navbahor', 'Navbahor', 'Навбахар', 'Навбаҳор', 8, now(), true, 'Navbahor Tumani'),
    (99, 'Konimex', 'Konimekx', 'Канимех', 'Конимех', 8, now(), true, 'Konimex Tumani'),
    (100, 'Karmana', 'Karmana', 'Кармана', 'Кармана', 8, now(), true, 'Karmana Tumani'),
    (101, 'Qiziltepa', 'Kiziltepa', 'Кызылтепа', 'Қизилтепа', 8, now(), true, 'Qiziltepa Tumani'),
    (102, 'Navoiy', 'Navai', 'Навои', 'Навоий', 8, now(), true, 'Navoiy Tumani'),
    (103, 'Nurota', 'Nurata', 'Нурата', 'Нурота', 8, now(), true, 'Nurota Tumani'),
    (104, 'Tomdi', 'Tomdi', 'Тамды', 'Томди', 8, now(), true, 'Tomdi Tumani'),
    (105, 'Uchquduq', 'Uchkuduk', 'Учкудук', 'Учқудуқ', 8, now(), true, 'Uchquduq Tumani'),
    (106, 'Xatirchi', 'Khatirchi', 'Хатирчи', 'Хатирчи', 8, now(), true, 'Xatirchi Tumani'),

-- Namangan viloyati
    (107, 'Chortoq', 'Chortak', 'Чартак', 'Чартак', 9, now(), true, 'Chortoq Tumani'),
    (108, 'Davlatobod', 'Davlatobod', 'Давлатабад', 'Давлатобод', 9, now(), true, 'Davlatobod Tumani'),
    (109, 'Chust', 'Chust', 'Чуст', 'Чуст', 9, now(), true, 'Chust Tumani'),
    (110, 'Yangiqo‘rg‘on', 'Yangikurgan', 'Янгикорган', 'Янгикўрғон', 9, now(), true, 'Yangiqo‘rg‘on Tumani'),
    (111, 'Kosonsoy', 'Kosonsoy', 'Касансай', 'Косонсой', 9, now(), true, 'Kosonsoy Tumani'),
    (112, 'Namangan', 'Namangan', 'Наманган', 'Наманган', 9, now(), true, 'Namangan Tumani'),
    (113, 'Pop', 'Pop', 'Пап', 'Поп', 9, now(), true, 'Pop Tumani'),
    (114, 'Uychi', 'Uychi', 'Уйчи', 'Уйчи', 9, now(), true, 'Uychi Tumani'),
    (115, 'Toʻraqoʻrgʻon', 'Turakurgon', 'Туракурган', 'Тўракурган', 9, now(), true, 'Toʻraqoʻrgʻon Tumani'),
    (116, 'Uchqoʻrgʻon', 'Uchquduk', 'Учкурган', 'Учқўрғон', 9, now(), true, 'Uchqoʻrgʻon Tumani'),
    (117, 'Mingbuloq', 'Mingbulok', 'Минбулаг', 'Минбулақ', 9, now(), true, 'Mingbuloq Tumani'),
    (118, 'Norin', 'Norin', 'Норин', 'Норин', 9, now(), true, 'Norin Tumani'),

-- Samarqand viloyati
    (119, 'Bulungʻur', 'Bulungur', 'Булунгур', 'Булунгур', 10, now(), true, 'Bulungʻur Tumani'),
    (120, 'Jomboy', 'Jomboy', 'Джамбай', 'Джамбай', 10, now(), true, 'Jomboy Tumani'),
    (121, 'Narpay', 'Narpay', 'Нарпай', 'Нарпай', 10, now(), true, 'Narpay Tumani'),
    (122, 'Oqdaryo', 'Okdaryo', 'Акдарьинский', 'Оқдарё', 10, now(), true, 'Oqdaryo Tumani'),
    (123, 'Pastarg‘om', 'Pastargom', 'Пастдаргомский', 'Пастдарғом', 10, now(), true, 'Pastarg‘om Tumani'),
    (124, 'Ishtixon', 'Ishtikhan', 'Иштыхан', 'Иштixon', 10, now(), true, 'Ishtixon Tumani'),
    (125, 'Kattaqoʻrgʻon', 'Kattakorgan', 'Каттакурган', 'Каттакўрған', 10, now(), true, 'Kattaqoʻrgʻon Tumani'),
    (126, 'Qoʻshrobod', 'Kushrobod', 'Кушрабад', 'Қўшробод', 10, now(), true, 'Qoʻshrobod Tumani'),
    (127, 'Paxtachi', 'Pakhtachi', 'Пахтачийский', 'Пахтачи', 10, now(), true, 'Paxtachi Tumani'),
    (128, 'Nurobod', 'Nurobod', 'Нурабад', 'Нурабод', 10, now(), true, 'Nurobod Tumani'),
    (129, 'Payariq', 'Payariq', 'Пайарык', 'Пайарық', 10, now(), true, 'Payariq Tumani'),
    (130, 'Samarqand', 'Samarkand', 'Самарканд', 'Самарқанд', 10, now(), true, 'Samarqand Tumani'),
    (131, 'Tayloq', 'Taylok', 'Тайлак', 'Тoйлoк', 10, now(), true, 'Toyloq Tumani'),
    (132, 'Urgut', 'Urgut', 'Ургут', 'Ургут', 10, now(), true, 'Urgut Tumani'),

-- Surxondaryo
    (133, 'Angor', 'Angor', 'Ангор', 'Ангор', 11, now(), true, 'Angor Tumani'),
    (134, 'Boysun', 'Boysun', 'Байсун', 'Бойсун', 11, now(), true, 'Boysun Tumani'),
    (135, 'Bandixon', 'Bandikhan', 'Бандихон', 'Бандихон', 11, now(), true, 'Bandixon Tumani'),
    (136, 'Denov', 'Denav', 'Денау', 'Денов', 11, now(), true, 'Denov Tumani'),
    (137, 'Jarqoʻrgʻon', 'Jurakurgon', 'Джаркурган', 'Джаркурган', 11, now(), true, 'Jarqoʻrgʻon Tumani'),
    (138, 'Qiziriq', 'Kizirik', 'Кизирик', 'Кизирик', 11, now(), true, 'Qiziriq Tumani'),
    (139, 'Qumqoʻrgʻon', 'Kumkurgon', 'Кумкурган', 'Кумкурган', 11, now(), true, 'Qumqoʻrgʻon tumani'),
    (140, 'Muzrobod', 'Muzrobod', 'Музрабад', 'Музрабад', 11, now(), true, 'Muzrobod Tumani'),
    (141, 'Sariosiyo', 'Sariosiyo', 'Сариасия', 'Сариасия', 11, now(), true, 'Sariosiyo Tumani'),
    (142, 'Sherobod', 'Sherobod', 'Шерабад', 'Шерабад', 11, now(), true, 'Sherobod Tumani'),
    (143, 'Shoʻrchi', 'Shurchi', 'Шурчи', 'Шурчи', 11, now(), true, 'Shoʻrchi Tumani'),
    (144, 'Termiz', 'Termiz', 'Термез', 'Термез', 11, now(), true, 'Termiz Tumani'),
    (145, 'Uzun', 'Uzun', 'Узун', 'Узун', 11, now(), true, 'Uzun tumani'),
    (146, 'Oltinsoy', 'Oltinsoy', 'Алтынсайский', 'Алтынсайский', 11, now(), true, 'Oltinsoy tumani'),

-- Sirdaryo
    (147, 'Boyovut', 'Boyovut', 'Баяут', 'Баяут', 12, now(), true, 'Boyovut Tumani'),
    (148, 'Sirdaryo', 'Sirdaryo', 'Сырдарья', 'Сырдарья', 12, now(), true, 'Sirdaryo Tumani'),
    (149, 'Guliston', 'Guliston', 'Гулистан', 'Гулистан', 12, now(), true, 'Guliston'),
    (150, 'Mirzaobod', 'Mirzaobod', 'Мирзаабадский', 'Мирзаабадский', 12, now(), true, 'Mirzaobod tumani'),
    (151, 'Oqoltin', 'Okoltin', 'Акалтынский', 'Акалтынский', 12, now(), true, 'Oqoltin Tumani'),
    (152, 'Sardora', 'Sardoba', 'Сардобский', 'Сардобский', 12, now(), true, 'Sardoba Tumani'),
    (153, 'Shirin', 'Shirin', 'Ширин', 'Ширин', 12, now(), true, 'Shirin'),
    (154, 'Xavos', 'Khavos', 'Хаваст', 'Хаваст', 12, now(), true, 'Xavos Tumani'),

-- Farg'ona
    (155, 'Oltiariq', 'Oltiarik', 'Алтыарык', 'Алтыарык', 13, now(), true, 'Oltiariq Tumani'),
    (156, 'Bogʻdod', 'Bogdod', 'Багдад', 'Багдад', 13, now(), true, 'Baghdod Tumani'),
    (157, 'Beshariq', 'Beshariq', 'Бешарык', 'Бешарык', 13, now(), true, 'Beshariq Tumani'),
    (158, 'Dangʻara', 'Dangara', 'Дангара', 'Дангара', 13, now(), true, 'Danghara Tumani'),
    (159, 'Fargʻona', 'Fergana', 'Фергана', 'Фергана', 13, now(), true, 'Farg''ona'),
    (160, 'Qoʻqon', 'Kukan', 'Коканд', 'Коканд', 13, now(), true, 'Qo‘qon'),
    (161, 'Quva', 'Kuva', 'Кува', 'Кува', 13, now(), true, 'Quwa Tumani'),
    (162, 'Quvasoy', 'Kuvasoy', 'Кувасай', 'Кувасай', 13, now(), true, 'Quvasoy'),
    (163, 'Yozyovon', 'Yozyovon', 'Язъяванский', 'Язъяванский', 13, now(), true, 'Yozyowon Tumani'),
    (164, 'Margʻilon', 'Margilan', 'Маргилан', 'Маргилан', 13, now(), true, 'Margilan'),
    (165, 'Qo‘shtepa', 'Kushtepa', 'Куштепинский', 'Куштепинский', 13, now(), true, 'Qo‘shtepa'),
    (166, 'So‘x', 'Sukh', 'Сохский', 'Сохский', 13, now(), true, 'Soʻx Tumani'),
    (167, 'Rishton', 'Rishton', 'Риштан', 'Риштан', 13, now(), true, 'Rishton Tuman'),
    (168, 'Uchko‘prik', 'Uchkuprik', 'Учкуприкский', 'Учкуприкский', 13, now(), true, 'Uchkoʻprik tumani'),
    (169, 'Toshloq', 'Toshlok', 'Ташлак', 'Ташлак', 13, now(), true, 'Toshloq Tumani'),
    (170, 'O‘zbekiston', 'Uzbekistan', 'Узбекистанский', 'Узбекистанский', 13, now(), true, 'O‘zbekiston Tumani'),

-- Xorazm
    (171, 'Bogʻot', 'Bogot', 'Багат', 'Багат', 14, now(), true, 'Boghot Tumani'),
    (172, 'Gurlan', 'Gurlan', 'Гурлен', 'Гурлен', 14, now(), true, 'Gurlan Tumani'),
    (173, 'Yangibozor', 'Yangibozor', 'Янгибазарский', 'Янгибазарский', 14, now(), true, 'Yangibozor'),
    (174, 'Qoʻshkoʻpir', 'Kushkupir', 'Кошкупыр', 'Кошкупыр', 14, now(), true, 'Qoʻshkoʻpir Tumani'),
    (175, 'Tuproqqalʼa', 'Tuprokqala', 'Тупроккалинский', 'Тупроккалинский', 14, now(), true, 'Tuproqqalʼa Tumani'),
    (176, 'Shovot', 'Shovot', 'Шават', 'Шават', 14, now(), true, 'Shovot Tumani'),
    (177, 'Urganch', 'Urganch', 'Ургенч', 'Ургенч', 14, now(), true, 'Urganch Tumani'),
    (178, 'Xonqa', 'Khonqa', 'Ханка', 'Ханка', 14, now(), true, 'Xonqa Tumani'),
    (179, 'Xozarasp', 'Khozarasp', 'Хазарасп', 'Хазарасп', 14, now(), true, 'Xozarasp Tumani'),
    (180, 'Xiva', 'Khiva', 'Хива', 'Хива', 14, now(), true, 'Xiva Tumani'),
    (181, 'Yangiariq', 'Yangiariq', 'Янгиарык', 'Янгиарык', 14, now(), true, 'Yangiariq Tumani');