-- Tashkent city (Toshkent shahri)
INSERT INTO district (id, region_id, name_uz, name_ru, name_en, visible, create_date)
VALUES     (1, 1, 'Bektemir tumani', 'Бектемир тумани', 'Bektemir district', true, now()),
           (2, 1, 'Mirobod tumani', 'Миробод тумани', 'Mirobod district', true, now()),
           (3, 1, 'Mirzo Ulug‘bek tumani', 'Мирзо Улугбек тумани', 'Mirzo Ulug‘bekdistrict', true, now()),
           (4, 1, 'Sergeli tumani', 'Сергелий тумани', 'Sergeli district', true, now()),
           (5, 1, 'Olmazor tumani', 'Олмазор тумани', 'Olmazor district', true, now()),
           (6, 1, 'Uchtepa tumani', 'Учтепа тумани', 'Uchtepa district', true, now()),
           (7, 1, 'Shayxontohur tumani', 'Шайхонтой тумани', 'Shayxontohur district', true, now()),
           (8, 1, 'Yashnobod tumani', 'Яшнобод тумани', 'Yashnobod district', true, now()),
           (9, 1, 'Chilonzor tumani', 'Чилонзор тумани', 'Chilonzor district', true, now()),
           (10, 1, 'Yunusobod tumani', 'Юнусобод тумани', 'Yunusobod district', true, now()),
           (11, 1, 'Yakkasaroy tumani', 'Яккасарой тумани', 'Yakkasaroy district', true, now()),
           (12, 1, 'Tashkent City Center', 'Центр города Ташкент', 'Tashkent City Center', true, now()),
           -- Tashkent region (Toshkent viloyati)
           (13, 2, 'Angren tumani', 'Ангрен тумани', 'Angren district', true, now()),
           (14, 2, 'Bekobod tumani', 'Бекабад тумани', 'Bekobod district', true, now()),
           (15, 2, 'Olmaliq tumani', 'Олмалиқ тумани', 'Olmaliq district', true, now()),
           (16, 2, 'Ohangaron tumani', 'Охангарон тумани', 'Ohangaron district', true, now()),
           (17, 2, 'Nurafshon tumani', 'Нурафшон тумани', 'Nurafshon district', true, now()),
           (18, 2, 'Chirchiq tumani', 'Чирчик тумани', 'Chirchik district', true, now()),
           (19, 2, 'Yangiyo‘l tumani', 'Янгиюль тумани', 'Yangiyul district', true, now()),
--            (20, 2, 'Bekobod tumani', 'Бекабад тумани', 'Bekobod district', true, now()),
           (21, 2, 'Bo‘ka tumani', 'Бўка тумани', 'Buka district', true, now()),
           (22, 2, 'Bo‘stonliq tumani', 'Бўстонлиқ тумани', 'Bostanliq district', true, now()),
           (23, 2, 'Qibray tumani', 'Қибрай тумани', 'Qibray district', true, now()),
           (24, 2, 'Quyi Chirchiq tumani', 'Қуйи Чирчиқ тумани', 'Quyi Chirchiq district', true, now()),
           (25, 2, 'Oqqo‘rg‘on tumani', 'Оқўрғон тумани', 'Oqqo‘rg‘on district', true, now()),
--            (26, 2, 'Ohangaron tumani', 'Охангарон тумани', 'Ohangaron district', true, now()),
           (27, 2, 'Parkent tumani', 'Паркент тумани', 'Parkent district', true, now()),
           (28, 2, 'Piskent tumani', 'Пискент тумани', 'Piskent district', true, now()),
--            (29, 2, 'Toshkent tumani', 'Тошкент тумани', 'Tashkent', true, now()),
           (30, 2, 'Zangiota tumani', 'Зангиота тумани', 'Zangiota district', true, now()),
           (31, 2, 'O‘rta Chirchiq tumani', 'Ўрта Чирчиқ тумани', 'O‘rta Chirchiq district', true, now()),
           (32, 2, 'Chinoz tumani', 'Чиноз тумани', 'Chinoz district', true, now()),
           (33, 2, 'Yuqori Chirchiq tumani', 'Юқори Чирчиқ', 'Yuqori Chirchiq district', true, now()),
--            (34, 2, 'Yangiyo‘l tumani', 'Янгиюль тумани', 'Yangiyul district', true, now()),
           -- Andijon region (Andijon viloyati)
           (35, 3, 'Kuyganyor tumani', 'Куйганйор тумани', 'Kuyganyor district', true, now()),
           (36, 3, 'Asaka tumani', 'Асака тумани', 'Asaka district', true, now()),
           (37, 3, 'Baliqchi tumani', 'Балиқчи тумани', 'Baliqchi district', true, now()),
           (38, 3, 'Boʻz tumani', 'Бўз тумани', 'Boʻz district', true, now()),
           (39, 3, 'Buloqboshi tumani', 'Булоқбоши тумани', 'Buloqboshi district', true, now()),
           (40, 3, 'Poytugʻ tumani', 'Пойтўқ тумани', 'Poytugʻ district', true, now()),
           (41, 3, 'Jalaquduq tumani', 'Жалақудуқ тумани', 'Jalaquduq district', true, now()),
           (42, 3, 'Xoʻjaobod tumani', 'Хўжаобод тумани', 'Xoʻjaobod district', true, now()),
           (43, 3, 'Qoʻrgʻontepa tumani', 'Қўрғонтепа тумани', 'Qoʻrgʻontepa district', true, now()),
           (44, 3, 'Marhamat tumani', 'Марҳамат тумани', 'Marhamat district', true, now()),
           (45, 3, 'Oltinkoʻl tumani', 'Олтинқўл тумани', 'Oltinkoʻl district', true, now()),
           (46, 3, 'Paxtaobod tumani', 'Пахтаобод тумани', 'Paxtaobod district', true, now()),
           (47, 3, 'Shahrixon tumani', 'Шахрихон тумани', 'Shahrixon district', true, now()),
           (48, 3, 'Oqoltin tumani', 'Оқўлтин тумани', 'Oqoltin district', true, now()),
           (49, 3, 'Xonobod tumani', 'Хонобод тумани', 'Xonobod district', true, now()),
           (50, 3, 'Andijon tumani', 'Андижон тумани', 'Andijon district', true, now()),
           -- Bukhara region (Buxoro viloyati)
           (51, 4, 'Olot tumani', 'Олот тумани', 'Olot district', true, now()),
           (52, 4, 'Galaosiyo tumani', 'Галаосиё тумани', 'Galaosiyo district', true, now()),
           (53, 4, 'Gʻijduvon tumani', 'Гиждувон тумани', 'Gʻijduvon district', true, now()),
           (54, 4, 'Jondor tumani', 'Жондор тумани', 'Jondor district', true, now()),
           (55, 4, 'Kogon tumani', 'Когон тумани', 'Kogon district', true, now()),
           (56, 4, 'Qorakoʻl tumani', 'Қорақўл тумани', 'Qorakoʻl district', true, now()),
           (57, 4, 'Qorovulbozor tumani', 'Қоровулбозор тумани', 'Qorovulbozor district', true, now()),
           (58, 4, 'Peshku tumani', 'Пешку тумани', 'Peshku district', true, now()),
           (59, 4, 'Romitan tumani', 'Ромитан тумани', 'Romitan district', true, now()),
           (60, 4, 'Shofirkon tumani', 'Шофиркон тумани', 'Shofirkon district', true, now()),
           (61, 4, 'Vobkent tumani', 'Вобкент тумани', 'Vobkent district', true, now()),
           -- Fergana region (Farg‘ona viloyati)
           (62, 5, 'Oltiariq tumani', 'Олтиариқ тумани', 'Oltiariq district', true, now()),
           (63, 5, 'Bagʻdod tumani', 'Багʻдод тумани', 'Bagʻdod district', true, now()),
           (64, 5, 'Beshariq tumani', 'Бешариқ тумани', 'Beshariq district', true, now()),
           (65, 5, 'Buvayda tumani', 'Бувайда тумани', 'Buvayda district', true, now()),
           (66, 5, 'Dangʻara tumani', 'Данғара тумани', 'Dangʻara district', true, now()),
           (67, 5, 'Vodil tumani', 'Водил тумани', 'Vodil district', true, now()),
           (68, 5, 'Navbahor tumani', 'Навбаҳор тумани', 'Navbahor district', true, now()),
           (69, 5, 'Langar tumani', 'Лангар тумани', 'Langar district', true, now()),
           (70, 5, 'Quva tumani', 'Қува тумани', 'Quva district', true, now()),
           (71, 5, 'Rishton tumani', 'Риштон тумани', 'Rishton district', true, now()),
           (72, 5, 'Ravon tumani', 'Равон тумани', 'Ravon district', true, now()),
           (73, 5, 'Toshloq tumani', 'Тошлоқ тумани', 'Toshloq district', true, now()),
           (74, 5, 'Uchkoʻprik tumani', 'Учкўприк тумани', 'Uchkoʻprik district', true, now()),
           (75, 5, 'Yaypan tumani', 'Яйпан тумани', 'Yaypan district', true, now()),
           (76, 5, 'Yozyovon tumani', 'Ёзёвон тумани', 'Yozyovon district', true, now()),
           -- Jizzakh region (Jizzax viloyati)
           (77, 6, 'Gʻoliblar tumani', 'Голиблар тумани', 'Gʻoliblar district', true, now()),
           (78, 6, 'O‘smat tumani', 'Ўсмат тумани', 'O‘smat district', true, now()),
           (79, 6, 'Doʻstlik tumani', 'Дўстлик тумани', 'Doʻstlik district', true, now()),
           (80, 6, 'Yangiqishloq tumani', 'Янгиқишлоқ тумани', 'Yangiqishloq district', true, now()),
           (81, 6, 'Gʻallaorol tumani', 'Ғаллаорол тумани', 'Gʻallaorol district', true, now()),
           (82, 6, 'Uch tepa tumani', 'Уч тепа тумани', 'Uch tepa district', true, now()),
           (83, 6, 'Gagarin tumani', 'Гагарин тумани', 'Gagarin district', true, now()),
           (84, 6, 'Paxtakor tumani', 'Пахтакор тумани', 'Paxtakor district', true, now()),
           (85, 6, 'Balandchaqir tumani', 'Баландчакир тумани', 'Balandchaqir district', true, now()),
           (86, 6, 'Zomin tumani', 'Зомин тумани', 'Zomin district', true, now()),
           (87, 6, 'Zafarobod tumani', 'Зафаробод тумани', 'Zafarobod district', true, now()),
           (88, 6, 'Zarbdor tumani', 'Зарбдор тумани', 'Zarbdor district', true, now()),
            -- Khorezm region (Xorazm viloyati)
           (89, 7, 'Bogʻot tumani', 'Боғот тумани', 'Bogʻot district', true, now()),
           (90, 7, 'Gurlan tumani', 'Гурлан тумани', 'Gurlan district' , true, now()),
           (91, 7, 'Xonqa tumani', 'Хонқа тумани', 'Xonqa district', true, now()),
           (92, 7, 'Pitnak tumani', 'Питнак тумани', 'Pitnak district', true, now()),
           (93, 7, 'Xiva tumani', 'Хива тумани', 'Xiva district ', true, now()),
           (94, 7, 'Qoʻshkoʻpir tumani', 'Қўшкўпир тумани', 'Qoʻshkoʻpir district', true, now()),
           (95, 7, 'Shovot tumani', 'Шовот тумани', 'Shovot district', true, now()),
           (96, 7, 'Qorovul tumani', 'Қоровул тумани', 'Qorovul district', true, now()),
           (97, 7, 'Yangiariq tumani', 'Янгиарик тумани', 'Yangiariq district', true, now()),
           (98, 7, 'Yangibozor tumani', 'Янгибозор тумани', 'Yangibozor district', true, now()),
           (99, 7, 'Hazorasp tumani', 'Ҳазорасп тумани', 'Hazorasp district', true, now()),
           -- Namangan region (Namangan viloyati)
           (100, 8, 'Chortoq tumani', 'Чортоқ тумани', 'Chortoq district', true, now()),
           (101, 8, 'Chust tumani', 'Чуст тумани', 'Chust district', true, now()),
           (102, 8, 'Kosonsoy tumani', 'Косонсо́й тумани', 'Kosonsoy district', true, now()),
           (103, 8, 'Mingbuloq tumani', 'Мингбулоқ тумани', 'Mingbuloq district', true, now()),
           (104, 8, 'Namangan tumani', 'Наманган тумани', 'Namangan district', true, now()),
           (105, 8, 'Haqqulobod tumani', 'Ҳаққулобод тумани', 'Haqqulobod district', true, now()),
           (106, 8, 'Pop tumani', 'Поп тумани', 'Pop district ', true, now()),
           (107, 8, 'Toʻraqoʻrgʻon tumani', 'Тўрақўрғон тумани', 'Toʻraqoʻrgʻon district', true, now()),
           (108, 8, 'Uchqoʻrgʻon tumani', 'Учқўрғон тумани', 'Uchqoʻrgʻon district', true, now()),
           (109, 8, 'Uychi tumani', 'Ўйчи тумани', 'Uychi district ', true, now()),
           (110, 8, 'Yangiqoʻrgʻon tumani', 'Янгиқўрғон тумани', 'Yangiqoʻrgʻon district', true, now()),
           (111, 8, 'Davlatobod tumani', 'Давлатобод тумани', 'Davlatobod district', true, now()),
           (112, 8, 'Yangi Namangan tumani', 'Янги Наманган тумани', 'Yangi Namangan district', true, now()),
           -- Navoi region (Navoiy viloyati)
           (113, 9, 'Konimex tumani', 'Конимек тумани', 'Konimex district', true, now()),
           (114, 9, 'Karmana tumani', 'Карманa тумани', 'Karmana district', true, now()),
           (115, 9, 'Qiziltepa tumani', 'Қизилтепа тумани', 'Qiziltepa district', true, now()),
           (116, 9, 'Yangirabot tumani', 'Янгирадёт тумани', 'Yangirabot district', true, now()),
           (117, 9, 'Beshrabot tumani', 'Бешрабад тумани', 'Beshrabot district', true, now()),
           (118, 9, 'Nurota tumani', 'Нурота тумани', 'Nurota district', true, now()),
           (119, 9, 'Tomdibuloq tumani', 'Томдибулоқ тумани', 'Tomdibuloq district', true, now()),
           (120, 9, 'Uchquduq tumani', 'Учқудуқ тумани', 'Uchquduq district', true, now()),
           -- Kashkadarya region (Qashqadaryo viloyati)
           (121, 10, 'Qorashina tumani', 'Қорашина тумани', 'Qorashina district', true, now()),
           (122, 10, 'Mugʻlon tumani', 'Мўғлон тумани', 'Mugʻlon district', true, now()),
           (123, 10, 'Kitob tumani', 'Китоб тумани', 'Kitob district', true, now()),
           (124, 10, 'Koson tumani', 'Қосон тумани', 'Koson district', true, now()),
           (125, 10, 'Yettitom tumani', 'Йеттитом тумани', 'Yettitom district', true, now()),
           (126, 10, 'Yangi Mirishkor tumani', 'Янги Миришкор тумани', 'Yangi Mirishkor district', true, now()),
           (127, 10, 'Muborak tumani', 'Муборак тумани', 'Muborak district', true, now()),
           (128, 10, 'Yangi Nishon tumani', 'Янги Нишон тумани', 'Yangi Nishon district', true, now()),
           (129, 10, 'Qamashi tumani', 'Қамаши тумани', 'Qamashi district', true, now()),
           (130, 10, 'Beshkent tumani', 'Бешкент тумани', 'Beshkent district', true, now()),
           (131, 10, 'Yakkabogʻ tumani', 'Яккабаг тумани', 'Yakkabogʻ district', true, now()),
           (132, 10, 'Gʻuzor tumani', 'Ғузор тумани', 'Gʻuzor district', true, now()),
           (133, 10, 'Chorshanba tumani', 'Чоршанба тумани', 'Chorshanba district', true, now()),
           (134, 10, 'Chiroqchi tumani', 'Чироқчи тумани', 'Chiroqchi district', true, now()),
           -- Republic of Karakalpakstan (Qoraqalpog‘iston Respublikasi)
           (135, 11, 'Mangʻit tumani', 'Мангит тумани', 'Mangit district', true, now()),
           (136, 11, 'Beruniy tumani', 'Беруни тумани', 'Beruniy district', true, now()),
           (137, 11, 'Chimboy tumani', 'Чимбой тумани', 'Chimboy district', true, now()),
           (138, 11, 'Boʻston tumani', 'Бўстон тумани', 'Bostan district', true, now()),
           (139, 11, 'Kegeyli tumani', 'Кегейли тумани', 'Kegeyli district', true, now()),
           (140, 11, 'Moʻynoq tumani', 'Мўйноқ тумани', 'Moʻynoq district', true, now()),
           (141, 11, 'Oqmangʻit tumani', 'Оқмангит тумани', 'Oqmangit district', true, now()),
           (142, 11, 'Qanlikoʻl tumani', 'Қанликўл тумани', 'Qanlikoʻl district', true, now()),
           (143, 11, 'Qoʻngʻirot tumani', 'Қўнғирот тумани', 'Qoʻngʻirot district', true, now()),
           (144, 11, 'Qoraoʻzak tumani', 'Қораўзак тумани', 'Qoraoʻzak district', true, now()),
           (145, 11, 'Shoʻmanoy tumani', 'Шўманоё тумани', 'Shoʻmanoy district', true, now()),
           (146, 11, 'Taxtakoʻpir tumani', 'Тахтакўпир тумани', 'Taxtakoʻpir district', true, now()),
           (147, 11, 'Toʻrtkoʻl tumani', 'Тўртқўл тумани', 'Toʻrtkoʻl district', true, now()),
           (148, 11, 'Xoʻjayli tumani', 'Хўжайли тумани', 'Xoʻjayli district', true, now()),
           -- Samarkand region (Samarqand viloyati)
           (149, 12, 'Qoʻshrabot tumani', 'Қўшрабо тумани', 'Qoʻshrabot district', true, now()),
           (150, 12, 'Narpay tumani', 'Нарпай тумани', 'Narpay district', true, now()),
           (151, 12, 'Nurobod tumani', 'Нуробод тумани', 'Nurobod district', true, now()),
           (152, 12, 'Oqdaryo tumani', 'Оқдарё тумани', 'Oqdaryo district', true, now()),
           (153, 12, 'Paxtachi tumani', 'Пахтачи тумани', 'Paxtachi district', true, now()),
           (154, 12, 'Payariq tumani', 'Пайариқ тумани', 'Payariq district', true, now()),
           (155, 12, 'Pastdargʻom tumani', 'Пастдарғом тумани', 'Pastdargʻom district', true, now()),
           (156, 12, 'Samarqand tumani', 'Самарқанд тумани', 'Samarkand district', true, now()),
           (157, 12, 'Toyloq tumani', 'Тойлоқ тумани', 'Toyloq district', true, now()),
           (158, 12, 'Urgut tumani', 'Ургут тумани', 'Urgut district', true, now()),
           -- Syrdarya region (Sirdaryo viloyati)
           (159, 13, 'Oq oltin tumani', 'Оқ алтын тумани', 'Oq oltin district', true, now()),
           (160, 13, 'Boyovut tumani', 'Боювут тумани', 'Boyovut district', true, now()),
           (161, 13, 'Dehqonobod tumani', 'Дехконобод тумани', 'Dehqonobod district', true, now()),
           (162, 13, 'Xovos tumani', 'Ховос тумани', 'Xovos district', true, now()),
           (163, 13, 'Navroʻz tumani', 'Навруз тумани', 'Navruz district', true, now()),
           (164, 13, 'Paxta obod tumani', 'Пахта обод тумани', 'Paxta obod district', true, now()),
           (165, 13, 'Sayxunobod tumani', 'Сайхунобод тумани', 'Sayxunobod district', true, now()),
           (166, 13, 'Sirdaryo tumani', 'Сирдарё тумани', 'Sirdaryo district', true, now()),
            -- Surxondaryo region (Surxondaryo viloyati)
           (167, 14, 'Angor tumani', 'Ангор тумани', 'Angor district', true, now()),
           (168, 14, 'Bandixon tumani', 'Бандихон тумани', 'Bandixon district', true, now()),
           (169, 14, 'Boysun tumani', 'Бойсун тумани', 'Boysun district', true, now()),
           (170, 14, 'Denov tumani', 'Денов тумани', 'Denov district', true, now()),
           (171, 14, 'Jarqoʻrgʻon tumani', 'Жаркургон тумани', 'Jarqorgon district', true, now()),
           (172, 14, 'Qiziriq tumani', 'Қизириқ тумани', 'Qiziriq district', true, now()),
           (173, 14, 'Qumqoʻrgʻon tumani', 'Қумқўрғон тумани', 'Qumqorgon district', true, now()),
           (174, 14, 'Muzrabod tumani', 'Музрабод тумани', 'Muzrabod district', true, now()),
           (175, 14, 'Oltinsoy tumani', 'Олтинсой тумани', 'Oltinsoy district', true, now()),
           (176, 14, 'Sariosiyo tumani', 'Сариосиё тумани', 'Sariosiyo district', true, now()),
           (177, 14, 'Sherobod tumani', 'Шеробод тумани', 'Sherobod district', true, now()),
           (178, 14, 'Shoʻrchi tumani', 'Шорчи тумани', 'Shorch district', true, now()),
           (179, 14, 'Termiz tumani', 'Термиз тумани', 'Termiz district', true, now()),
           (180, 14, 'Uzun tumani', 'Узун тумани', 'Uzun district', true, now());
